package pkg

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"aic/internal/parse"
)

// ---------------------------------------------------------------------------
// 测试单元装载（核心设计 §十一：aic test 发现 *_test.aic，func testXxx 约定）。
//
// 单元构成 = 测试文件所在目录的**普通源文件**（*_test.aic 不入包） + 该测试文件
// + 合成的 main（按发现序逐个调用 testXxx）。合成 main 写在临时文件里，只借用
// 一个路径做 #line 回指，不进语料、不进包目录。
//
// 为什么不让测试文件自带 main：约定就是 `func testXxx()`——零参无返回、被运行器
// 收集；自带 main 的测试文件是普通程序（用 aic build 跑），两者不混。
// ---------------------------------------------------------------------------

// TestUnit 是一个测试程序（包 + 测试文件 + 合成入口）。
type TestUnit struct {
	// Unit 是整程序（入口包含测试文件与合成 main）。
	Unit *Unit
	// Tests 是按声明序收集到的 testXxx 函数名。
	Tests []string
}

// LoadTest 装载一个测试文件所在的包（含该测试文件与合成 main）。
func LoadTest(testFile string) (*TestUnit, error) {
	abs, err := filepath.Abs(testFile)
	if err != nil {
		return nil, fmt.Errorf("aic: cannot locate %s: %v", testFile, err)
	}
	dir := filepath.Dir(abs)
	base := filepath.Base(abs)
	if !strings.HasSuffix(base, "_test.aic") {
		return nil, diag(parse.Pos{File: relPath(abs), Line: 1, Col: 1},
			"a test file must end with _test.aic", base,
			"rename it to <name>_test.aic (core design §11: aic test discovers *_test.aic)")
	}
	// 包 = 目录里的普通源文件（没有普通文件时允许只有测试文件）。
	var p *Package
	if hasPlainSource(dir) {
		p, err = loadPackage(dir, parse.Pos{File: relPath(abs), Line: 1, Col: 1})
		if err != nil {
			return nil, err
		}
	} else {
		p = &Package{Name: filepath.Base(dir), Dir: dir, ImportPos: map[string]parse.Pos{}}
	}
	tf, err := parseFileAt(dir, base, "")
	if err != nil {
		return nil, err
	}
	p.Files = append(p.Files, tf)
	for _, d := range tf.AST.Decls {
		im, ok := d.(*parse.ImportDecl)
		if !ok {
			continue
		}
		if _, dup := p.ImportPos[im.Name]; !dup {
			p.ImportPos[im.Name] = im.Pos
			p.Imports = append(p.Imports, im.Name)
		}
	}
	tests := collectTests(tf.AST)
	if len(tests) == 0 {
		return nil, diag(parse.Pos{File: relPath(abs), Line: 1, Col: 1},
			"no testXxx function in the test file", base,
			"write func testXxx() { testing.eq(actual, expected, \"note\") } (no params, no result)")
	}
	mainFile, err := writeTestMain(dir, base, tests)
	if err != nil {
		return nil, err
	}
	p.Files = append(p.Files, mainFile)
	l := &loader{
		entryPos: parse.Pos{File: relPath(abs), Line: 1, Col: 1},
		byDir:    map[string]*Package{dir: p},
		state:    map[string]int{},
	}
	if err := l.walk(p); err != nil {
		return nil, err
	}
	return &TestUnit{Unit: &Unit{Entry: p, Order: l.order}, Tests: tests}, nil
}

// collectTests 按声明序收集零参无返回的 testXxx 函数。
func collectTests(f *parse.File) []string {
	var out []string
	for _, d := range f.Decls {
		fd, ok := d.(*parse.FuncDecl)
		if !ok || fd.Extern || fd.Body == nil {
			continue
		}
		if !strings.HasPrefix(fd.Name, "test") || len(fd.Name) == len("test") {
			continue
		}
		if len(fd.Params) != 0 || len(fd.Results) != 0 {
			continue // 约定：零参无返回
		}
		out = append(out, fd.Name)
	}
	return out
}

// hasPlainSource 报告目录里是否有非测试源文件。
func hasPlainSource(dir string) bool {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".aic") && !strings.HasSuffix(e.Name(), "_test.aic") {
			return true
		}
	}
	return false
}

// writeTestMain 生成合成入口（逐个调用 testXxx）并解析为 File。
func writeTestMain(dir, testBase string, tests []string) (*File, error) {
	var b strings.Builder
	b.WriteString("// generated by aic test: calls every testXxx in declaration order (do not edit).\n")
	b.WriteString("func main() {\n")
	for _, t := range tests {
		b.WriteString("\t" + t + "()\n")
	}
	b.WriteString("}\n")
	f, err := os.CreateTemp("", "aic-test-main-*.aic")
	if err != nil {
		return nil, fmt.Errorf("aic test: cannot create the synthetic entry: %v", err)
	}
	src := b.String()
	if _, err := f.WriteString(src); err != nil {
		f.Close()
		return nil, fmt.Errorf("aic test: cannot write the synthetic entry: %v", err)
	}
	f.Close()
	rel := relPath(f.Name())
	ast, lexErrs, parseErrs := parse.Source(rel, src)
	if len(lexErrs) > 0 || len(parseErrs) > 0 {
		return nil, &SyntaxError{Path: rel, Lex: lexErrs, Parse: parseErrs}
	}
	return &File{Path: rel, Src: src, AST: ast}, nil
}
